name: "Dependency review"
on: # yamllint disable-line rule:truthy
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    dependency-review:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411" # v2.19.4
              with:
                  egress-policy: "audit"

            - name: "Git checkout"
              uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Dependency Review"
              uses: "actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294" # v5.0.0
        permissions:
            contents: "read"
            pull-requests: "write"
        uses: "anolilab/workflows/.github/workflows/dependency-review.yml@5b340a228896b01f6d2b6f3bf3b574caed9ee89b" # v15.3.1+
